# Generated by Django 2.2.7 on 2019-11-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0004_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image2',
        ),
    ]
