# Generated by Django 2.2.7 on 2019-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0006_auto_20191127_0108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
